# Generated by Django 5.1.1 on 2024-09-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('travel', 'Travel'), ('diet', 'Diet'), ('energy', 'Energy')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('travel', 'Travel'), ('diet', 'Diet'), ('energy', 'Energy')], max_length=50)),
                ('suggestion_text', models.TextField()),
                ('impact_reduction_estimate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_items', models.TextField()),
                ('calories_consumed', models.FloatField()),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet', to='forecasts.activity')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_usage_kwh', models.FloatField()),
                ('appliances_used', models.TextField()),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='energy', to='forecasts.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_carbon_footprint', models.FloatField()),
                ('predicted_energy_usage', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='forecasts.activity')),
            ],
        ),
        migrations.CreateModel(
            name='TravelActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('mode_of_transport', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('bike', 'Bike'), ('walk', 'Walk')], max_length=50)),
                ('duration_hours', models.FloatField()),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='forecasts.activity')),
            ],
        ),
    ]
